version: '3.8'

services: 
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=pass@123
      - DOCKER_INFLUXDB_INIT_ORG=IUDX 
      - DOCKER_INFLUXDB_INIT_BUCKET=COVID
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  backend:
    build: ./backend
    image: covidtracker-backend-compose
    environment:
      - INFLUXDB_TOKEN=2g3UODxp-hNTePRDsDwSj_j1ZWI3JbvdMIxVRO9BQDu34O4Ctkqg7XsxWPcKAXlGSAaZWj1Kc-lpi94RwIIJAw==
      - PORT=4444
      - DATABASE_URL=http://influxdb:8086
      - INFLUXDB_ORG=IUDX
      - INFLUXDB_BUCKET=COVID
    depends_on:
      - influxdb
    ports:
      - 4444:4444
    stdin_open: true
    tty: true
    restart: on-failure
  frontend:
    build: ./frontend
    image: covidtracker-frontend-compose
    ports:
      - 3000:80
    stdin_open: true

volumes: 
  influxdb-storage:


